default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: volt_dev
  username: postgres
  host: localhost

test:
  <<: *development
  database: volt_test

production:
  url: <%= ENV['DATABASE_URL'] %>
